# Generated by Django 3.2.9 on 2021-12-03 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='_user_rented',
            field=models.TextField(default='{"users": []}'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.CharField(default='', max_length=60, validators=[django.core.validators.RegexValidator(message='Invalid preview', regex='^[a-zA-Z0-9,.?! ]+$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Doesn't match ISBN pattern", regex='^(?=(?:\\D*\\d){10}(?:(?:\\D*\\d){3})?$)[\\d-]+$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid author', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Invalid description', regex='^[a-zA-Z0-9,.?! ]+$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=10000)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid title', regex='^[a-zA-Z0-9 ]+$')]),
        ),
    ]
