# Generated by Django 3.2.9 on 2021-12-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211203_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='text',
        ),
    ]
